# Generated by Django 2.2.2 on 2019-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('dspecialist', models.CharField(max_length=30)),
                ('dcontact', models.IntegerField()),
                ('dage', models.IntegerField()),
            ],
        ),
    ]
